% This script obtains the WM estimates from different tracts that were generated by the CamCAN pipelines

clear all; clc

cd('/Volumes/STD-Donders-DCC-Geerligs/')

%directory where the results will be saved
savedir= '/Volumes/STD-Donders-DCC-Geerligs/Michelle/VSTM/Extracted_data/';

%load the behavioral data 
subdata= load([savedir 'subject_info.mat']);

%load which subjects need to be included
load([savedir 'extracted_data.mat'], 'insub')

%location of the data
WMdir='/Volumes/STD-Donders-DCC-Geerligs/Cambridge_data/MRI_data/cc700/mri/pipeline/release004/data_DWI_DKI_JHU_ICBM/aamod_diffusion_roi_extract_dki_00002/';
statdir='/Volumes/STD-Donders-DCC-Geerligs/Cambridge_data/MRI_data/cc700/mri/pipeline/release004/aamod_structuralstats_00001/';

%collect the WM and TIV data for all participants
clear TIV WMdata1
for i=1:length(subdata.CCID)
    disp(i)
    ID=['CC' num2str(subdata.CCID(i))];
    stats=load([statdir ID '/structurals/structuralstats.mat']);
    TIV(i)=stats.S.TIV.vox;
    if exist([WMdir ID '/Diffusion/ROI_aamod_diffusion_dkifit_00001.dki_MK.mat'])
        WM=load([WMdir ID '/Diffusion/ROI_aamod_diffusion_dkifit_00001.dki_MK.mat']);
        WMdata1(i,:)=[WM.ROI.mean];
    else
        WMdata1(i,:)=NaN;
    end
end

%there are two tracts with no coverage (19 and 20) which are removed here
%these are the superior longitudinal fasciculus (temporal part) L and R
WMdata=WMdata1(:,1:18);
covs_WM=TIV';

%These are the labels of the WM tracts in the correct order
labels={'Anterior thalamic radiation L','Anterior thalamic radiation R','Corticospinal tract L',.....
'Corticospinal tract R','Cingulum (cingulate gyrus) L','Cingulum (cingulate gyrus) R','Cingulum (hippocampus) L',.....
'Cingulum (hippocampus) R','Forceps major','Forceps minor','Inferior fronto-occipital fasciculus L',.....
'Inferior fronto-occipital fasciculus R','Inferior longitudinal fasciculus L','Inferior longitudinal fasciculus R',.....
'Superior longitudinal fasciculus L','Superior longitudinal fasciculus R','Uncinate fasciculus L','Uncinate fasciculus R'};

%This stripe index was used to determine the quality of the diffusion data. Data with a lot of head motion show horizontal stripes
load(['/Volumes/Wrkgrp/STD-Donders-DCC-Geerligs/Cambridge_data/Karen_synchrony/stripe_data.mat'], 'stripe_data')
%load(['/home/lingee/wrkgrp/Cambridge_data/Karen_synchrony/stripe_data.mat'], 'stripe_data')
for i=1:length(subdata.CCID)
    disp(i)
    ID=['CC' num2str(subdata.CCID(i))];
    subind=find(strcmp(stripe_data(:,2),ID));
    if~isempty(subind)
        stripeind(i)=str2num(stripe_data{subind,3});
    else
        stripeind(i)=NaN;
    end
end

%get 'cleaned' WM data by excluding subjects who have to many stripes and by excluding outliers per tract
WMdata_clean=ones(size(WMdata)).*NaN;
for n=1:18
    ind=find(~isnan(WMdata(:,n))&(stripeind'<=0.1)); % use this to include subjects without too much striping
    %ind=find(~isnan(WMdata(:,n))&(stripeind'>0.1)); %to find which subjects were excluded because of striping
    outlier=[find(WMdata(:,n)<(nanmean(WMdata(ind,n))-3*nanstd(WMdata(ind,n)))); find(WMdata(:,n)>(nanmean(WMdata(:,n))+3*nanstd(WMdata(:,n))))];
    ind=setdiff(ind, outlier);
    WMdata_clean(ind,n)=WMdata(ind,n);
end

%Note that the following subjects still need to be excluded: 22, 29,
%54, 79, 91, 100. Participants 45, 61, and 26 were already excluded as part
%of the WM cleaning. 

% with the below step you get rid of the subjects that were excluded
% previously
% WMdata_clean=WMdata_clean(insub,1:18);

%create different WM variables with different variables regressed out (e.g. average WM, TIV, age) in different combinations. 
WMres_TIV=ones(size(WMdata)).*NaN;
WMres_ageTIV=ones(size(WMdata)).*NaN;
WMres_mWM=ones(size(WMdata)).*NaN;
WMres_agemWM=ones(size(WMdata)).*NaN;
WMres_age=ones(size(WMdata)).*NaN;
meanWM=nanmean(WMdata_clean,2)'; %calculates mean WM across all tracts for each subject
t_subs=zeros(size(WMdata,2));
for n=1:18
    ind=find(~isnan(WMdata_clean(:,n)));
    [b,bint,WMres_mWM(ind,n)] =     regress(WMdata(ind,n), [meanWM(ind); ones(size(TIV(ind)))]');
    [b,bint,WMres_TIV(ind,n)] =     regress(WMdata(ind,n), [TIV(ind); ones(size(TIV(ind)))]');
    [b,bint,WMres_ageTIV(ind,n)] =  regress(WMdata(ind,n), [TIV(ind);subdata.age(ind); ones(size(TIV(ind)))]');
    [b,bint,WMres_agemWM(ind,n)] =  regress(WMdata(ind,n), [meanWM(ind);subdata.age(ind); ones(size(TIV(ind)))]');
    [b,bint,WMres_age(ind,n)] =     regress(WMdata(ind,n), [subdata.age(ind); ones(size(TIV(ind)))]');
    %figure out how many subjects are left for each tract
    t_subs(n)=length(ind);
end


% do the same for the mean WM. 
mWMres_TIV=ones(size(meanWM)).*NaN;
mWMres_ageTIV=ones(size(meanWM)).*NaN;
ind=find(~isnan(meanWM));
[b,bint,mWMres_TIV(ind)] = regress(meanWM(ind)', [TIV(ind); ones(size(TIV(ind)))]');
[b,bint,mWMres_ageTIV(ind)] = regress(meanWM(ind)', [TIV(ind); subdata.age(ind); ones(size(TIV(ind)))]');


save([savedir 'WMdata.mat'], 'stripeind','TIV', 'WMdata_clean', 'labels', 'WMres_TIV',....
   'WMres_ageTIV', 'meanWM', 'WMres_mWM', 'WMres_agemWM', 'mWMres_TIV', 'mWMres_ageTIV', "WMres_age");