% This script obtains the GM estimates from all ROIs and averages them within networks. The GM estimates were generated by the CamCAN pipelines

clear all; clc

%directory where the results will be saved
savedir = '/Volumes/STD-Donders-DCC-Geerligs/Michelle/VSTM/Extracted_data/'

%load the behavioral data 
subdata= load([savedir 'subject_info.mat']);

%location of the data
GMdir = '/Volumes/STD-Donders-DCC-Geerligs/Cambridge_data/MRI_data/cc280/mri/pipeline/release003/Structural/aamod_dartel_normmni_00001/';
ICVdir='/Volumes/STD-Donders-DCC-Geerligs/MRI_data/cc280/mri/pipeline/release003/Structural/aamod_structuralstats_00001/';

%file for brain parcellation
roifile='/Volumes/Wrkgrp/STD-Donders-DCC-Geerligs/Michelle/VSTM/Craddock_ROIs_JNpaper_reordered.nii';

%load module labels for data averaging
load([savedir 'module_data.mat'], 'final_community')
load([savedir 'extracted_data.mat'], 'insub','ROI2include')

nsub=length(subdata.CCID);
numberofROI=748;
ROIdataGM = zeros(nsub, numberofROI);
TIV_280= zeros(nsub, 1);
TGM_280= zeros(nsub, 1);

% extract GM for parcels
for i=1:nsub
    disp(i)
    ID=['CBU' num2str(subdata.CBUID2(i))];
    if exist([ICVdir ID '/structurals/structuralstats.mat'],'file')
       %load TGM and TIV
       S = load([ICVdir ID '/structurals/structuralstats.mat']);
       TGM_280(i)=S.S.parts.mm3_spm12(1);
       TIV_280(i)=S.S.TIV.mm3_spm12;
       names = dir([GMdir ID '/structurals/*.nii']);
       GMfname = {[GMdir ID '/structurals/' names(1).name]};
        
       %extract mean GM per ROI
       SR=[];
       SR.no_svd = 1;SR.zero_rel_tol = 0.5;SR.zero_abs_tol = 1;SR.output_raw=1;SR.mask_space=0;
       SR.Datafiles{1}=GMfname;
       SR.ROIfiles={roifile};
       ROI = roi_extract(SR);
       ROIdataGM(i,:)=[ROI(:).rawdata];
       nvoxGM=[ROI(:).numvox];

    else
       TIV_280(i)=NaN;
       TGM_280(i)=NaN;
       ROIdataGM(i,:)=NaN;
   end
end

save([savedir 'ROIdataGM.mat'], 'ROIdataGM', 'TIV_280', 'TGM_280','nvoxGM')


%% Beware that the final GM variables only contain subjects with valid GM and VSTM data! 
%This is different from the WM analysis as for WM there are
%subject-specific drop-outs of particular tracts. 

%identify subjects with valid GM and VSTM data
ROIdataGM_ROIin=ROIdataGM(insub,ROI2include);

%identify subjects with valid GM data
GMin=find(~isnan(ROIdataGM_ROIin(:,1))); %2 subjects do not have valid GM data
TIVdata=TIV_280(insub(GMin)); %ICV
TGMdata=TGM_280(insub(GMin)); %Total GM

%average GM per network
subjAverage_GM_network=zeros(length(GMin),max(final_community));
for nNetworks=1:max(final_community)   
    subjAverage_GM_network(:,nNetworks)=mean((ROIdataGM_ROIin(GMin,find(final_community==nNetworks))),2);
end 

%regress out TIV and TGM from GM
GMres_ageTGM=zeros(size(subjAverage_GM_network));
GMres_TGM=zeros(size(subjAverage_GM_network));
GMres_TIV=zeros(size(subjAverage_GM_network));
GMres_TIVage=zeros(size(subjAverage_GM_network));
GMres_TIVageTGM=zeros(size(subjAverage_GM_network));
for nNetworks=1:max(final_community)
    [b,bint,GMres_ageTGM(:,nNetworks)] = regress(subjAverage_GM_network(:,nNetworks), [TGMdata subdata.age(insub(GMin))' ones(size(TIVdata))]);
    [b,bint,GMres_TGM(:,nNetworks)] = regress(subjAverage_GM_network(:,nNetworks), [TGMdata ones(size(TIVdata))]);
    [b,bint,GMres_TIV(:,nNetworks)] = regress(subjAverage_GM_network(:,nNetworks), [TIVdata ones(size(TIVdata))]);
    [b,bint,GMres_TIVage(:,nNetworks)] = regress(subjAverage_GM_network(:,nNetworks), [TIVdata subdata.age(insub(GMin))' ones(size(TIVdata))]);
    [b,bint,GMres_TIVageTGM(:,nNetworks)] = regress(subjAverage_GM_network(:,nNetworks), [TIVdata subdata.age(insub(GMin))' TGMdata ones(size(TIVdata))]);
end
[b,bint,TGMres_ageTIV]=regress(TGMdata, [TIVdata subdata.age(insub(GMin))' ones(size(TIVdata))]);
[b,bint,TGMres_TIV]=regress(TGMdata, [TIVdata ones(size(TIVdata))]);

save([savedir 'network_dataGM.mat'], 'subjAverage_GM_network', 'GMres_ageTGM', 'TGMres_ageTIV', 'GMin', ...
    'TIVdata', 'TGMdata', 'TGMres_TIV', 'GMres_TGM', 'GMres_TIV', 'GMres_TIVage', 'GMres_TIVageTGM')


